//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsusFanControlGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int fanSpeed {
            get {
                return ((int)(this["fanSpeed"]));
            }
            set {
                this["fanSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool turnOffControlOnExit {
            get {
                return ((bool)(this["turnOffControlOnExit"]));
            }
            set {
                this["turnOffControlOnExit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool forbidUnsafeSettings {
            get {
                return ((bool)(this["forbidUnsafeSettings"]));
            }
            set {
                this["forbidUnsafeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool minimizeToTrayOnClose {
            get {
                return ((bool)(this["minimizeToTrayOnClose"]));
            }
            set {
                this["minimizeToTrayOnClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoRefreshStats {
            get {
                return ((bool)(this["autoRefreshStats"]));
            }
            set {
                this["autoRefreshStats"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useFanCurve {
            get {
                return ((bool)(this["useFanCurve"]));
            }
            set {
                this["useFanCurve"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool startWithWindows {
            get {
                return ((bool)(this["startWithWindows"]));
            }
            set {
                this["startWithWindows"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fansOffOnSleep {
            get {
                return ((bool)(this["fansOffOnSleep"]));
            }
            set {
                this["fansOffOnSleep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int fanCurvePointCount {
            get {
                return ((int)(this["fanCurvePointCount"]));
            }
            set {
                this["fanCurvePointCount"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool useGpuCurve {
            get {
                return ((bool)(this["useGpuCurve"]));
            }
            set {
                this["useGpuCurve"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int cpuCurveTemp1 {
            get {
                return ((int)(this["cpuCurveTemp1"]));
            }
            set {
                this["cpuCurveTemp1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int cpuCurveFan1 {
            get {
                return ((int)(this["cpuCurveFan1"]));
            }
            set {
                this["cpuCurveFan1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int cpuCurveTemp2 {
            get {
                return ((int)(this["cpuCurveTemp2"]));
            }
            set {
                this["cpuCurveTemp2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int cpuCurveFan2 {
            get {
                return ((int)(this["cpuCurveFan2"]));
            }
            set {
                this["cpuCurveFan2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int cpuCurveTemp3 {
            get {
                return ((int)(this["cpuCurveTemp3"]));
            }
            set {
                this["cpuCurveTemp3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int cpuCurveFan3 {
            get {
                return ((int)(this["cpuCurveFan3"]));
            }
            set {
                this["cpuCurveFan3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public int gpuCurveTemp1 {
            get {
                return ((int)(this["gpuCurveTemp1"]));
            }
            set {
                this["gpuCurveTemp1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45")]
        public int gpuCurveFan1 {
            get {
                return ((int)(this["gpuCurveFan1"]));
            }
            set {
                this["gpuCurveFan1"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55")]
        public int gpuCurveTemp2 {
            get {
                return ((int)(this["gpuCurveTemp2"]));
            }
            set {
                this["gpuCurveTemp2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int gpuCurveFan2 {
            get {
                return ((int)(this["gpuCurveFan2"]));
            }
            set {
                this["gpuCurveFan2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75")]
        public int gpuCurveTemp3 {
            get {
                return ((int)(this["gpuCurveTemp3"]));
            }
            set {
                this["gpuCurveTemp3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int gpuCurveFan3 {
            get {
                return ((int)(this["gpuCurveFan3"]));
            }
            set {
                this["gpuCurveFan3"] = value;
            }
        }

    }
}
